# -*- coding: utf-8 -*-
import json

# English to Bulgarian translations for products
translations = {
    "SmartWatch Pro": "SmartWatch Pro",
    "Smartwatch with heart rate tracking and GPS.": "Умен часовник с проследяване на сърдечния ритъм и GPS.",
    "Fitness Band X": "Фитнес Лента X",
    "Lightweight fitness tracker with sleep monitoring.": "Лек фитнес проследяч със мониторинг на сън.",
    "NoiseCancel Headphones": "Слушалки със шумоизолация",
    "Wireless headphones with active noise cancellation.": "Безжични слушалки с активна шумоизолация.",
    "Bluetooth Earbuds": "Bluetooth Слушалки",
    "True wireless earbuds with charging case.": "Истински безжични слушалки с кейс за зареждане.",
    "Smart Home Hub": "Интелигентен домашен хъб",
    "Central hub for managing smart home devices.": "Централен хъб за управление на устройства на умния дом.",
    "Smart Light Bulb": "Интелигентна крушка",
    "Wi-Fi enabled LED light bulb with color control.": "LED крушка с Wi-Fi и контрол на цвета.",
    "Smart Plug": "Интелигентна щепсела",
    "Control appliances remotely using a smart plug.": "Управлявайте уреди отдалечено с интелигентна щепсела.",
    "Robot Vacuum": "Робот прахосмукачка",
    "Automatic vacuum cleaner with scheduling.": "Автоматична прахосмукачка с планиране.",
    "Air Purifier": "Пречиствател на въздух",
    "Removes allergens and pollutants from the air.": "Премахва алергени и замърсители от въздуха.",
    "Electric Kettle": "Електричен чайник",
    "Fast-boiling electric kettle with auto shut-off.": "Бърз електричен чайник с автоматично изключване.",
    "Coffee Maker": "Кафемашина",
    "Programmable coffee maker with timer.": "Програмируема кафемашина с таймер.",
    "Espresso Machine": "Машина за еспресо",
    "Compact espresso machine for home use.": "Компактна машина за еспресо за домашна употреба.",
    "Blender Pro": "Блендер Pro",
    "High-speed blender for smoothies and soups.": "Висока скорост блендер за смути и супи.",
    "Toaster Oven": "Тостерна фурна",
    "Multi-function toaster oven with convection.": "Многофункционална тостерна фурна с конвекция.",
    "Gaming Mouse": "Игровая мишка",
    "High-precision gaming mouse with RGB lighting.": "Прецизна игровая мишка с RGB осветление.",
    "Mechanical Keyboard": "Механична клавиатура",
    "Mechanical keyboard with tactile switches.": "Механична клавиатура с тактилни превключватели.",
    "Laptop Stand": "Поставка за лаптоп",
    "Adjustable aluminum laptop stand.": "Регулируема алуминиева поставка за лаптоп.",
    "USB-C Hub": "USB-C хъб",
    "Multi-port USB-C hub with HDMI output.": "Мултипортов USB-C хъб с HDMI изход.",
    "External SSD 1TB": "Външен SSD 1TB",
    "High-speed portable solid-state drive.": "Бърз преносим твърд диск.",
    "Wireless Charger": "Безжично зарядно устройство",
    "Fast wireless charging pad.": "Бързо безжично зареждащо подложка.",
    "Smartphone Gimbal": "Смартфон Gimbal",
    "Stabilizer for smooth mobile video recording.": "Стабилизатор за гладко мобилно видео записване.",
    "Action Camera": "Екшън камера",
    "Waterproof action camera with 4K recording.": "Водоустойчива екшън камера с 4K записване.",
    "Tripod Stand": "Тринога поставка",
    "Lightweight tripod for cameras and phones.": "Лека тринога за камери и телефони.",
    "Dash Camera": "Dash камера",
    "Car dash cam with night vision.": "Автомобилна тире камера с нощно виждане.",
    "Car Phone Mount": "Държател за телефон в автомобила",
    "Dashboard phone mount with adjustable grip.": "Държател за телефон за табло с регулируем хват.",
    "Portable Power Bank": "Преносима батерия",
    "10,000mAh power bank for mobile devices.": "10 000 mAh батерия за мобилни устройства.",
    "Solar Power Bank": "Соларна батерия",
    "Solar-powered battery pack for outdoor use.": "Батерия на сонячна енергия за открита употреба.",
    "Smart Thermostat": "Интелигентен термостат",
    "Energy-saving smart thermostat with app control.": "Енергоспестяващ интелигентен термостат с управление през приложение.",
    "Security Camera": "Охранна камера",
    "Wi-Fi security camera with motion detection.": "Wi-Fi охранна камера с обнаружение на движение.",
    "Video Doorbell": "Видеодомофон",
    "Smart doorbell with live video streaming.": "Интелигентен звънец с директно видео потоци.",
    "Smart Lock": "Интелигентна брава",
    "Keyless smart door lock with app access.": "Интелигентна брава без ключ с достъп през приложение.",
    "Wireless Router": "Безжичен маршрутизатор",
    "High-speed dual-band Wi-Fi router.": "Висока скорост двулентов Wi-Fi маршрутизатор.",
    "Mesh Wi-Fi System": "Mesh Wi-Fi система",
    "Whole-home mesh Wi-Fi coverage.": "Mesh Wi-Fi покритие за целия дом.",
    "Monitor 27-inch": "Монитор 27 инча",
    "27-inch full HD computer monitor.": "27-инчев монитор Full HD.",
    "Webcam HD": "Webcam HD",
    "1080p webcam for video conferencing.": "1080p уеб камера за видео конференции.",
    "Desk Lamp": "Работна лампа",
    "LED desk lamp with brightness control.": "LED работна лампа с контрол на яркостта.",
    "Ergonomic Chair": "Ергономичен стол",
    "Office chair with lumbar support.": "Офисен стол с поддържка на долния гръб.",
    "Standing Desk": "Стол за стояние",
    "Height-adjustable standing desk.": "Регулируемо по височина бюро за стояние.",
    "Notebook Cooler": "Охлаждане за лаптоп",
    "Cooling pad for laptops.": "Охлаждаща подложка за лаптопи.",
    "Smart Scale": "Интелигентна везна",
    "Digital scale with body composition analysis.": "Цифрова везна с анализ на състава на тялото.",
    "Blood Pressure Monitor": "Монитор за кръвно налягане",
    "Home blood pressure monitoring device.": "Устройство за мониторинг на кръвното налягане у дома.",
    "Electric Toothbrush": "Електрическа четка за зъби",
    "Rechargeable electric toothbrush.": "Преоредима електрическа четка за зъби.",
    "Hair Dryer": "Сешоар",
    "High-power hair dryer with heat control.": "Мощен сешоар с контрол на топлина.",
    "Smart TV 55-inch": "Smart TV 55 инча",
    "55-inch 4K smart television.": "55-инчев 4K интелигентен телевизор.",
    "Soundbar": "Звукова лента",
    "Home theater soundbar with subwoofer.": "Звукова лента за домашния кинотеатър със събвуфер.",
    "Game Controller": "Игров контролер",
    "Wireless controller for gaming consoles.": "Безжичен контролер за игрови конзоли.",
    "VR Headset": "VR слушалки",
    "Virtual reality headset for immersive gaming.": "VR слушалки за вълнуващи игри.",
    "Smart Projector": "Интелигентен проектор",
    "Portable projector with Wi-Fi support.": "Преносим проектор с Wi-Fi поддръжка.",
    "E-Reader": "E-четец",
    "Glare-free e-reader with backlight.": "E-четец без бликане със светлина отзад.",
    "Tablet 10-inch": "Таблет 10 инча",
    "10-inch tablet for work and entertainment.": "10-инчев таблет за работа и развлечение.",
    "Smart Pen": "Интелигентна писалка",
    "Stylus pen for tablets.": "Стилус писалка за таблети.",
    "Graphics Tablet": "Графичен таблет",
    "Drawing tablet for designers.": "Таблет за рисуване за дизайнери.",
    "Label Printer": "Принтер за етикети",
    "Compact label printer for home office.": "Компактен принтер за етикети за домашен офис.",
    "Paper Shredder": "Разсипвач на хартия",
    "Cross-cut paper shredder.": "Кръстосан разсипвач на хартия.",
    "Portable Scanner": "Преносим скенер",
    "Handheld document scanner.": "Преносим скенер за документи.",
    "Smart Alarm Clock": "Интелигентен будилник",
    "Alarm clock with voice assistant.": "Будилник с гласов асистент.",
    "Digital Photo Frame": "Цифрова фотографска рамка",
    "Wi-Fi digital photo frame.": "Wi-Fi цифрова фотографска рамка.",
    "Weather Station": "Метеорологична станция",
    "Indoor and outdoor weather monitoring.": "Мониторинг на вътрешната и външната температура.",
    "Pet Camera": "Домашна животинска камера",
    "Camera for monitoring pets remotely.": "Камера за отдалечено наблюдение на домашни животни.",
    "Automatic Pet Feeder": "Автоматична хранилка за домашни животни",
    "Smart feeder with scheduled meals.": "Интелигентна хранилка с планирани хранения.",
    "Electric Scooter": "Електрически скутер",
    "Foldable electric scooter for commuting.": "Сгъваем електрически скутер за пътуване.",
    "Smart Bike Lock": "Интелигентна брава за велосипед",
    "Bluetooth-enabled bike lock.": "Блютут брава за велосипед.",
    "Portable Speaker": "Преносим говорител",
    "Bluetooth speaker with deep bass.": "Блютут говорител с дълбок бас.",
    "Studio Microphone": "Студио микрофон",
    "USB microphone for streaming and podcasts.": "USB микрофон за стриймване и подкасти.",
    "Pop Filter": "Pop филтър",
    "Microphone pop filter for clear audio.": "Pop филтър за микрофон за ясен звук.",
    "Ring Light": "Кръгла светлина",
    "LED ring light for video recording.": "LED кръгла светлина за видео записване.",
    "Green Screen": "Зелен екран",
    "Portable green screen backdrop.": "Преносим зелен екран фон.",
    "Streaming Capture Card": "Streaming карта за захват",
    "Capture card for game streaming.": "Карта за захват за игро потоци.",
    "Network Switch": "Мрежов превключвател",
    "8-port gigabit network switch.": "8-портов гигабитен мрежов превключвател.",
    "Firewall Router": "Маршрутизатор с защита",
    "Secure router with firewall features.": "Защитен маршрутизатор с функции защита.",
    "NAS Storage": "NAS хранилище",
    "Network attached storage for backups.": "Мрежово хранилище за резервни копия.",
    "Memory Card 256GB": "Памет карта 256GB",
    "High-capacity SD memory card.": "SD памет карта с голяма капацитет.",
    "USB Flash Drive 128GB": "USB флаш памет 128GB",
    "Portable USB flash storage.": "Преносимо USB хранилище.",
    "Cable Organizer": "Организатор на кабели",
    "Cable management box for desks.": "Кутия за управление на кабели.",
    "Surge Protector": "Защита от скок на напрежението",
    "Power strip with surge protection.": "Разклонител с защита от скок.",
    "Smart Smoke Detector": "Интелигентен детектор за дим",
    "Wi-Fi smoke and carbon monoxide detector.": "Wi-Fi детектор за дим и въглероден оксид.",
    "Water Leak Sensor": "Датчик за течове на вода",
    "Detects water leaks and sends alerts.": "Обнаружава течове на вода и изпраща предупреждения.",
    "Garage Door Controller": "Контролер за гаражна врата",
    "Smart controller for garage doors.": "Интелигентен контролер за гаражни врати.",
    "Smart Irrigation System": "Интелигентна система за напояване",
    "Automated garden watering system.": "Автоматизирана система за напояване на градина.",
    "Outdoor Security Light": "Външна охранна светлина",
    "Motion-activated outdoor light.": "Външна светлина, активирана от движение.",
    "Portable Generator": "Преносимо електрогенератор",
    "Compact generator for emergency power.": "Компактен генератор за аварийно захранване.",
    "Camping Lantern": "Палатка светлина",
    "Rechargeable LED camping lantern.": "Преоредима LED палатка светлина.",
    "Smart Water Bottle": "Интелигентна бутилка за вода",
    "Tracks daily water intake.": "Проследява дневното потребление на вода.",
    "Massage Gun": "Масажен пистолет",
    "Deep tissue massage device.": "Устройство за масаж на дълбоки тъкани.",
    "Yoga Mat": "Мат за йога",
    "Non-slip yoga mat.": "Мат за йога без хлъзгане.",
    "Resistance Bands": "Еластични ленти",
    "Set of resistance bands for workouts.": "Комплект еластични ленти за тренировки.",
    "Treadmill": "Трака за бягане",
    "Foldable treadmill for home workouts.": "Сгъваема трака за бягане за домашни тренировки.",
    "Smart Rowing Machine": "Интелигентна гребна машина",
    "Connected rowing machine with app support.": "Свързана гребна машина с поддръжка на приложение.",
    "Digital Thermometer": "Цифров термометър",
    "Fast-reading digital thermometer.": "Бързочитаем цифров термометър.",
    "UV Sanitizer Box": "UV санитайзер кутия",
    "UV box for sanitizing small items.": "UV кутия за санитизиране на малки предмети.",
    "Smart Mirror": "Интелигентно огледало",
    "Interactive mirror with display.": "Интерактивно огледало с дисплей.",
    "Electric Blanket": "Электрическо одеяло",
    "Heated blanket with temperature control.": "Нагрявано одеяло с контрол на температурата.",
    "Humidifier": "Овлажнител",
    "Cool mist humidifier for rooms.": "Овлажнител с прохладна мъгла за стаи.",
    "Dehumidifier": "Осушител",
    "Removes excess moisture from air.": "Премахва излишната влага от въздуха.",
    "Smart Fan": "Интелигентен вентилатор",
    "Wi-Fi enabled fan with app control.": "Wi-Fi вентилатор с контрол през приложение.",
    "Portable Air Conditioner": "Преносим климатик",
    "Mobile air conditioner unit.": "Мобилно хладилно устройство.",
    "Smart Refrigerator": "Интелигентен хладилник",
    "Connected refrigerator with touch display.": "Свързан хладилник с сензорен дисплей.",
    "Dishwasher": "Съдомиялна машина",
    "Energy-efficient dishwasher.": "Енергоспестяваща съдомиялна машина.",
    "Washing Machine": "Пералня",
    "Front-load washing machine.": "Предна пералня.",
    "Dryer": "Сушилня",
    "Electric clothes dryer.": "Електрическа сушилня.",
}

# Read current products
with open('data/products.json', 'r', encoding='utf-8') as f:
    products = json.load(f)

# Add Bulgarian translations
for product in products:
    name = product['name']
    desc = product['description']
    product['name_bg'] = translations.get(name, name)
    product['description_bg'] = translations.get(desc, desc)

# Write back
with open('data/products.json', 'w', encoding='utf-8') as f:
    json.dump(products, f, ensure_ascii=False, indent=2)

print(f"✓ Added Bulgarian translations to {len(products)} products")
